_wandb:
    value:
        cli_version: 0.21.3
        e:
            hc465si155agnpuuenocq83jow10ya1q:
                codePath: neural_detection_model.py
                codePathLocal: neural_detection_model.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2014574526464"
                        used: "381001535488"
                email: pony076152340@gmail.com
                executable: /home/bl515-ml/Documents/shaio_jie/ienf_q/.venv/bin/python3
                git:
                    commit: 640676aa0c6887e97c1534f9eceb4a28e726ee23
                    remote: https://github.com/Ponywen0819/ienf_q.git
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-9362d02e-7f8c-78a1-58df-19b99e1dc522
                host: bl515ml
                memory:
                    total: "134720536576"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/bl515-ml/Documents/shaio_jie/ienf_q/./neural_detection_model.py
                python: CPython 3.12.11
                root: /home/bl515-ml/Documents/shaio_jie/ienf_q
                startedAt: "2025-09-09T05:01:14.397806Z"
                writerId: hc465si155agnpuuenocq83jow10ya1q
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 16
            "4": 3.12.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
architecture:
    value: NeuralDetectionCNN
batch_size:
    value: 2
device:
    value: cuda
learning_rate:
    value: 0.001
loss_function:
    value: SpecialLoss
num_epochs:
    value: 50
patch_size:
    value: 256
